// Logros
function ach(){const vs=id=>S.z[id]=='v',vis=ALL.filter(z=>vs(z.id)).length,N=ALL.length,gr=g=>{const a=ALL.filter(z=>z.g==g);return[a.filter(z=>vs(z.id)).length,a.length]},g=(i,n,d,k)=>({id:i,n,d,c:gr(k)[0],m:gr(k)[1]});
const big=ALL.filter(z=>z.t&&z.g<5),leg=ALL.filter(z=>z.ly&&z.ly.length),wish=ALL.filter(z=>S.z[z.id]=='w').length,sur=gr(4)[0],nor=ALL.filter(z=>z.g<4&&vs(z.id)).length;
return[{id:'p',n:'Primer vítor',d:'Marca tu primer sitio como «He estado»',c:vis,m:1},{id:'e',n:'Explorador',d:'Pisa 10 zonas',c:vis,m:10},{id:'h',n:'Medio mapa',d:'Pisa la mitad de las zonas',c:vis,m:Math.ceil(N/2)},{id:'t',n:'Charro de pura cepa',d:'Pisa todas las zonas',c:vis,m:N},
g('k0','Casco completo','Pisa todo el casco histórico',0),g('k1','Norte completo','Pisa toda la zona norte',1),g('k2','Este completo','Pisa toda la zona este',2),g('k3','Oeste completo','Pisa toda la zona oeste',3),g('k4','Sur completo','Pisa todo el sur, al otro lado del río',4),g('k5','Vuelta al alfoz','Pisa los pueblos de alrededor',5),
{id:'gr',n:'Los grandes',d:'Pisa los grandes barrios (Garrido, Pizarrales, Prosperidad…)',c:big.filter(z=>vs(z.id)).length,m:big.length},
{id:'ly',n:'Cazador de leyendas',d:'Pisa todas las zonas que tienen leyenda',c:leg.filter(z=>vs(z.id)).length,m:leg.length},
{id:'rv',n:'Cruzar el Tormes',d:'Pisa 3 barrios del sur y 3 del norte',c:Math.min(sur,3)+Math.min(nor,3),m:6},
{id:'wi',n:'Soñador',d:'Apunta 5 sitios como «Quiero ir»',c:wish,m:5},{id:'fr',n:'Rana a la vista',d:'Encuentra la rana escondida en el mapa',c:S.f?1:0,m:1},{id:'g1',n:'Aquí mismo',d:'Marca un sitio estando en él, con el botón Estoy aquí',c:(S.gv||[]).length,m:1},{id:'g5',n:'Con las botas puestas',d:'Marca 5 sitios estando en ellos',c:(S.gv||[]).length,m:5},{id:'p1',n:'Saliendo del alfoz',d:'Pisa tu primer pueblo de la provincia (pestaña Provincia)',c:PALL.filter(m=>!m.z&&stM(m)=='v').length,m:1},{id:'p25',n:'Trotapueblos',d:'Pisa 25 pueblos de la provincia',c:PALL.filter(m=>stM(m)=='v').length,m:25},{id:'p100',n:'Charro de mapa entero',d:'Pisa 100 pueblos de la provincia',c:PALL.filter(m=>stM(m)=='v').length,m:100},{id:'pc',n:'Comarca completa',d:'Pisa todos los pueblos de una comarca',c:Math.max(...PRV.com.map((_,ci)=>{const a=PALL.filter(m=>m.c==ci);return a.filter(m=>stM(m)=='v').length/a.length})),m:1}]}
function renderAch(){const A=ach(),box=$('#lga'),ok=A.filter(a=>a.c>=a.m).length;box.textContent='';$('#lgs').textContent='Logros ('+ok+'/'+A.length+')';
A.forEach(a=>{const r=document.createElement('div'),st=document.createElement('span'),mid=document.createElement('div'),b=document.createElement('b'),sm=document.createElement('small'),pb=document.createElement('div'),i=document.createElement('i'),c=Math.min(a.c,a.m),done=a.c>=a.m;
r.className='ac'+(done?' ok':'');st.className='st';st.textContent=done?'★':'☆';mid.style.flex='1';b.textContent=a.n;sm.textContent=a.d+' · '+c+'/'+a.m;mid.append(b,sm);pb.className='pb';i.style.width=(c/a.m*100)+'%';pb.appendChild(i);r.append(st,mid,pb);box.appendChild(r)})}
$('#fr').onclick=()=>{const nw=!S.f;S.f=1;save();upd();toast('¡Has encontrado la rana!');if(nw)setTimeout(()=>toast('Logro: Rana a la vista'),1900)};
